In [1]:
#using https://www.youtube.com/watch?v=HR2amKqWU-8 as guide

In [2]:
import requests
from bs4 import BeautifulSoup as bs
import time
import pandas as pd

In [3]:
startTime = time.time()

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}

pages = []
for pageNo in range(1,5):
    urlStart = 'https://www.centralcharts.com/en/price-list-ranking/ALL/asc/ts_19-us-nasdaq-stocks--qc_1-alphabetical-order?p='
    url = urlStart + str(pageNo)
    pages.append(url)
result = []
for page in pages:
    webpage = requests.get(page, headers=headers)
    soup = bs(webpage.text, 'html.parser')

    stockTable = soup.find('table', class_ = 'tabMini tabQuotes')
    trTagList = stockTable.find_all('tr')

    for trTag in trTagList:
        tdTagList = trTag.find_all('td')

        rowValues = []
        for tdTag in tdTagList[0:8]:
            newValue = tdTag.text.strip()
            rowValues.append(newValue)
        result.append(rowValues)
print(result)
print("Time taken:", time.time() - startTime)

[[], ['1-800-FLOWERS.COM', '4.27', '-1.16%', '4.41', '4.41', '4.20', '222,698', '233M'], ['10X GENOMICS', '32.22', '+11.72%', '29.73', '32.33', '29.73', '4,477,135', '3,708M'], ['111', '4.57', '-6.54%', '4.81', '4.99', '4.43', '22,777', '39M'], ['17 EDUCATION & TECHNOLOGY', '2.39', '+1.70%', '2.41', '2.41', '2.35', '3,079', '22M'], ['1RT ACQUISITION', '10.23', '+0.00%', '10.23', '10.23', '10.23', '2,113', '145M'], ['1RT ACQUISITION', '10.32', '-0.10%', '10.32', '10.32', '10.32', '2,800', '147M'], ['1ST SOURCE', '77.40', '-1.43%', '78.69', '79.08', '77.21', '122,721', '1,368M'], ['1STDIBS.COM', '4.09', '+0.25%', '4.08', '4.23', '4.07', '111,962', '92M'], ['20/20 BIOLABS', '0.5957', '-38.12%', '0.7742', '0.7893', '0.5660', '3,552,263', '3M'], ['22ND CENTURY', '6.14', '-6.26%', '6.59', '6.60', '6.10', '50,446', '1M'], ['3 E NETWORK TECHNOLOGY', '2.41', '+1.69%', '2.37', '2.46', '2.25', '899,469', '120,435'], ['36KR', '2.99', '+2.05%', '2.91', '3.48', '2.83', '148,321', '3M'], ['374WATER', '2.31', '+0.00%', '2.35', '2.47', '2.22', '101,310', '21M'], ['4D MOLECULAR THERAPEUTICS', '9.22', '+4.42%', '9.04', '9.80', '9.04', '1,064,885', '358M'], ['5E ADVANCED MATERIALS', '1.71', '+0.59%', '1.73', '1.77', '1.71', '98,316', '11M'], ['60 DEGREES PHARMACEUTICALS', '1.49', '+9.56%', '1.43', '1.49', '1.37', '85,626', '1M'], ['707 CAYMAN', '2.19', '+0.46%', '2.10', '2.47', '2.10', '231,765', '1M'], ['8X8', '1.77', '-0.56%', '1.80', '1.86', '1.77', '1,206,364', '240M'], ['908 DEVICES', '8.62', '+4.23%', '8.62', '8.78', '8.46', '159,356', '243M'], ['9F', '2.88', '-2.04%', '3.20', '3.20', '2.88', '4,139', '13M'], ['A SPAC III ACQUISITION', '11.70', '+1.74%', '11.02', '11.70', '11.02', '941', '94M'], ['A SPAC III ACQUISITION RIGHT', '0.0900', '-10.89%', '0.1001', '0.1072', '0.0900', '31,631', '184,723'], ['A2Z CUST2MATE SOLUTIONS', '5.82', '-4.12%', '6.14', '6.18', '5.80', '295,620', '212M'], ['AAON', '131.26', '+3.20%', '133.53', '134.71', '131.07', '852,141', '8,927M'], ['AARDVARK THERAPEUTICS', '3.84', '-1.54%', '3.90', '4.10', '3.81', '206,297', '42M'], ['ABCELLERA BIOLOGICS', '5.26', '+0.38%', '5.49', '5.53', '5.17', '3,683,751', '1,080M'], ['ABEONA THERAPEUTICS', '5.67', '+2.53%', '5.54', '5.74', '5.54', '620,439', '206M'], ['ABITS', '1.33', '-2.21%', '1.36', '1.37', '1.29', '61,763', '2M'], ['ABIVAX', '98.26', '+1.77%', '99.60', '103.93', '95.70', '2,119,381', '5,783M'], ['ABLE VIEW GLOBAL', '1.11', '+0.91%', '1.08', '1.16', '1.08', '81,046', '25M'], [], ['ABONY ACQUISITION', '9.91', '+0.20%', '9.91', '9.91', '9.91', '1,008', '230M'], ['ABONY ACQUISITION', '10.10', '+0.00%', '10.03', '10.50', '10.03', '2,887', '235M'], ['ABSCI', '7.27', '+6.91%', '7.38', '7.74', '7.13', '6,683,656', '971M'], ['ABVC BIOPHARMA', '1.26', '+5.88%', '1.19', '1.29', '1.19', '92,308', '17M'], ['AC IMMUNE', '2.34', '+1.30%', '2.31', '2.38', '2.31', '144,148', '147M'], ['ACACIA RESEARCH', '4.70', '+0.43%', '4.70', '4.71', '4.64', '199,240', '448M'], ['ACADEMY SPORTS AND OUTDOORS', '49.25', '-3.45%', '51.17', '51.57', '49.10', '1,646,746', '3,125M'], ['ACADIA HEALTHCARE', '24.99', '+1.59%', '24.79', '25.01', '24.24', '2,455,896', '2,128M'], ['ACADIA PHARMACEUTICALS', '21.26', '+0.81%', '21.10', '21.39', '21.07', '1,209,876', '3,593M'], ['ACCO', '1.55', '-3.73%', '1.66', '1.66', '1.54', '83,527', '5M'], ['ACCURAY', '0.3217', '-5.74%', '0.3472', '0.3601', '0.3192', '1,956,802', '36M'], ['ACHIEVE LIFE SCIENCES', '5.60', '+1.45%', '5.64', '5.66', '5.32', '1,943,274', '489M'], ['ACI WORLDWIDE', '44.79', '-0.99%', '45.36', '45.65', '44.71', '805,142', '4,495M'], ['ACLARION', '3.03', '-2.88%', '3.20', '3.20', '2.93', '58,244', '2M'], ['ACLARIS THERAPEUTICS', '4.36', '+0.93%', '4.43', '4.53', '4.26', '1,675,522', '456M'], ['ACM RESEARCH', '95.21', '+1.34%', '97.55', '99.00', '94.50', '1,355,331', '5,258M'], ['ACNB', '56.48', '-1.77%', '57.67', '57.67', '56.21', '41,818', '554M'], ['ACORN ENERGY', '15.77', '-0.76%', '15.87', '16.00', '15.57', '8,462', '26M'], ['ACP ACQUISITION', '9.94', '+0.10%', '9.94', '9.94', '9.94', '50,465', '213M'], ['ACP ACQUISITION', '10.08', '+0.10%', '10.07', '10.08', '10.07', '11,732', '206M'], ['ACRIVON THERAPEUTICS', '1.52', '+2.70%', '1.55', '1.62', '1.52', '394,769', '34M'], ['ACTIVATE ENERGY ACQUISITION', '10.15', '+0.00%', '10.15', '11.05', '10.15', '855', '162M'], ['ACTIVATE ENERGY ACQUISITION', '9.99', '+0.00%', '9.99', '9.99', '9.99', '635', '0'], ['ACTUATE THERAPEUTICS', '2.05', '+1.49%', '2.14', '2.15', '1.97', '120,854', '18M'], ['ACUMEN PHARMACEUTICALS', '2.34', '-1.27%', '2.37', '2.44', '2.34', '280,544', '108M'], ['ACURX PHARMACEUTICALS', '1.57', '+0.00%', '1.62', '1.71', '1.57', '89,936', '2M'], ['ADAGENE', '3.64', '+1.96%', '3.62', '3.67', '3.59', '18,081', '96M'], ['ADAGIO MEDICAL', '0.7607', '+2.11%', '0.7600', '0.7699', '0.7537', '19,693', '12M'], ['ADAMAS TRUST', '9.28', '-0.32%', '9.43', '9.51', '9.23', '961,509', '838M'], ['ADAMAS TRUST 9.125% SENIOR NOTES DUE 20', '24.91', '-1.58%', '24.94', '24.98', '24.89', '19,104', '0'], [], ['ADAMAS TRUST 9.125% SENIOR NOTES DUE 20', '25.04', '-1.34%', '25.00', '25.14', '25.00', '18,941', '2,261M'], ['ADAMAS TRUST 9.250% SENIOR NOTES DUE 20', '24.96', '-1.38%', '24.91', '24.96', '24.85', '37,320', '721M'], ['ADAMAS TRUST 9.875% SENIOR NOTES DUE 20', '25.33', '-1.75%', '25.20', '25.36', '25.20', '41,201', '2,287M'], ['ADAMAS TRUST SERIES D FIXED-TO-FLOATING', '23.67', '+0.47%', '23.56', '23.78', '23.56', '5,651', '2,137M'], ['ADAMAS TRUST SERIES E FIXED-TO-FLOATING', '25.31', '+0.04%', '25.31', '25.40', '25.28', '30,063', '2,285M'], ['ADAMAS TRUST SERIES F FIXED-TO-FLOATING', '24.38', '+0.12%', '24.30', '24.43', '24.30', '13,145', '0'], ['ADAMAS TRUST SERIES G CUMULATIVE REDEEM', '19.03', '+0.79%', '19.00', '19.10', '18.99', '16,314', '0'], ['ADAPTHEALTH', '9.96', '-1.97%', '10.17', '10.17', '9.90', '1,225,615', '861M'], ['ADAPTIVE BIOTECHNOLOGIES', '17.46', '-0.80%', '18.38', '18.38', '17.13', '2,836,305', '2,697M'], ['ADDENTAX', '4.99', '+8.01%', '4.51', '4.99', '4.51', '12,539', '3M'], ['ADDEX THERAPEUTICS', '6.00', '-6.98%', '6.01', '6.40', '6.00', '8,529', '3M'], ['ADDUS HOMECARE', '94.83', '+1.66%', '93.35', '94.96', '91.82', '260,366', '1,720M'], ['ADEIA', '32.34', '+1.32%', '33.25', '33.25', '31.54', '1,408,126', '3,498M'], ['ADIAL PHARMACEUTICALS', '2.85', '-4.36%', '3.12', '3.12', '2.70', '246,260', '3M'], ['ADICET BIO', '8.11', '+0.75%', '8.12', '8.37', '8.11', '32,008', '67M'], ['ADITXT', '0.0129', '+1.57%', '0.0129', '0.0165', '0.0120', '717,718,225', '423'], ['ADLAI NORTYE', '11.33', '+9.79%', '10.07', '11.33', '10.07', '144,357', '143M'], ['ADMA BIOLOGICS', '8.50', '+3.53%', '8.26', '8.56', '8.22', '4,512,938', '1,927M'], ['ADOBE', '206.36', '+1.15%', '206.88', '211.90', '205.72', '9,660,892', '83,155M'], ['ADS-TEC ENERGY', '11.50', '+0.09%', '11.50', '11.50', '11.50', '1,524', '364M'], ['ADTRAN', '15.13', '-0.85%', '15.63', '15.73', '14.73', '4,120,731', '1,125M'], ['ADURO CLEAN TECHNOLOGIES', '14.81', '+4.30%', '14.80', '15.54', '14.47', '631,643', '331M'], ['ADVANCED BIOMED', '4.40', '-2.22%', '4.27', '5.00', '4.23', '114,509', '1M'], ['ADVANCED ENERGY INDUSTRIES', '370.66', '+4.60%', '372.35', '377.63', '365.43', '1,702,407', '13,944M'], ['ADVANCED FLOWER CAPITAL', '3.33', '-2.63%', '3.39', '3.51', '3.30', '310,650', '48M'], ['ADVANCED MICRO DEVICES', '547.26', '+6.98%', '535.75', '554.87', '530.50', '33,378,158', '887,579M'], ['ADVANTAGE SOLUTIONS', '38.90', '-0.77%', '39.51', '40.24', '37.90', '68,341', '165M'], ['AEBI SCHMIDT', '12.20', '-1.13%', '12.61', '12.69', '12.14', '110,195', '446M'], ['AEHR TEST SYSTEMS', '115.88', '+6.83%', '118.32', '122.00', '115.39', '1,619,156', '3,447M'], ['AELUMA', '24.93', '-1.07%', '26.50', '27.00', '24.01', '1,051,220', '247M'], [], ['AEMETIS', '1.91', '-2.55%', '1.97', '2.08', '1.91', '749,589', '125M'], ['AEON ACQUISITION', '10.07', '+0.10%', '10.06', '10.07', '10.06', '2,397', '0'], ['AERIES TECHNOLOGY', '5.37', '-7.41%', '6.31', '6.31', '5.25', '85,095', '42M'], ['AEROVIRONMENT', '171.95', '+0.80%', '174.41', '176.00', '169.40', '962,037', '6,445M'], ['AERSALE', '6.29', '+0.32%', '6.36', '6.48', '6.27', '449,965', '216M'], ['AETHER', '3.10', '-0.32%', '3.16', '3.16', '2.94', '10,177', '12M'], ['AETHLON MEDICAL', '2.00', '-0.99%', '2.07', '2.10', '1.96', '150,718', '28M'], ['AEVA TECHNOLOGIES', '26.87', '+7.96%', '26.77', '28.24', '26.45', '2,155,176', '1,130M'], ['AEYE', '1.61', '+0.63%', '1.64', '1.67', '1.61', '1,282,870', '70M'], ['AFFINITY BANCSHARES', '22.48', '-0.18%', '22.52', '22.52', '22.45', '51,918', '96M'], ['AFFIRM', '71.90', '+8.66%', '69.00', '73.45', '68.47', '6,479,322', '20,221M'], ['AFYA', '13.95', '-1.06%', '14.10', '14.45', '13.45', '187,584', '341M'], ['AGAPE ATP', '2.89', '+0.00%', '2.83', '2.89', '2.75', '74,531', '1M'], ['AGENCIA COMERCIAL SPIRITS', '14.15', '-1.74%', '14.41', '14.57', '13.80', '56,489', '322M'], ['AGENUS', '3.25', '-1.52%', '3.36', '3.44', '3.24', '454,656', '122M'], ['AGILYSYS', '87.49', '-3.48%', '90.72', '92.52', '85.99', '351,156', '2,329M'], ['AGIOS PHARMACEUTICALS', '31.82', '+8.01%', '29.69', '31.83', '29.26', '1,651,465', '1,773M'], ['AGM ORDINARY SHARES', '1.35', '+13.45%', '1.24', '1.43', '1.23', '246,373', '2M'], ['AGNC INVESTMENT', '10.46', '+1.45%', '10.46', '10.55', '10.40', '12,248,256', '11,928M'], ['AGNC INVESTMENT DEPOSITARY SHARES', '25.10', '+0.60%', '25.00', '25.10', '25.00', '7,687', '9,716M'], ['AGNC INVESTMENT DEPOSITARY SHARES', '25.31', '+0.28%', '25.23', '25.33', '25.21', '59,447', '9,825M'], ['AGNC INVESTMENT DEPOSITARY SHARES', '25.62', '+0.23%', '25.58', '25.62', '25.54', '18,062', '9,813M'], ['AGNC INVESTMENT DEPOSITARY SHARES', '25.92', '-0.08%', '25.88', '25.94', '25.85', '16,822', '8,833M'], ['AGNC INVESTMENT DEPOSITARY SHARES', '25.44', '+0.12%', '25.44', '25.45', '25.40', '31,495', '29,011M'], ['AGNC INVESTMENT DEPOSITARY SHARES REP S', '25.18', '+0.24%', '25.04', '25.25', '25.04', '14,021', '8,882M'], ['AGNT', '4.74', '+2.38%', '4.69', '4.97', '4.63', '1,158,676', '0'], ['AGOMAB THERAPEUTICS ADRS', '10.00', '+4.06%', '9.89', '10.14', '9.46', '158,923', '361M'], ['AGORA', '4.24', '-1.85%', '4.41', '4.47', '4.15', '427,051', '265M'], ['AGRICULTURE & NATURAL SOLUTIONS ACQUISI', '11.42', '+0.35%', '11.42', '11.42', '11.42', '1,808', '474M'], ['AGRICULTURE & NATURAL SOLUTIONS ACQUISI', '12.51', '+0.00%', '12.54', '13.45', '11.60', '7,796', '412M']]
Time taken: 3.153517484664917

In [4]:
columns = ['Financial instrument', 'Current price', 'Change(%)', 'Open', 'High', 'Low', 'Volume', 'Market Cap.']
df = pd.DataFrame(result, columns=columns)
df = df.iloc[1:]

In [5]:
df.head()

,Financial instrument,Current price,Change(%),Open,High,Low,Volume,Market Cap.
1,1-800-FLOWERS.COM,4.27,-1.16%,4.41,4.41,4.20,"222,698",233M
2,10X GENOMICS,32.22,+11.72%,29.73,32.33,29.73,"4,477,135","3,708M"
3,111,4.57,-6.54%,4.81,4.99,4.43,"22,777",39M
4,17 EDUCATION & TECHNOLOGY,2.39,+1.70%,2.41,2.41,2.35,"3,079",22M
5,1RT ACQUISITION,10.23,+0.00%,10.23,10.23,10.23,"2,113",145M

In [6]:
df.describe()

,Financial instrument,Current price,Change(%),Open,High,Low,Volume,Market Cap.
count,120,120,120,120,120,120,120,120
unique,110,118,106,115,117,118,120,99
top,AGNC INVESTMENT DEPOSITARY SHARES,2.34,+0.00%,4.41,4.99,10.07,"222,698",0
freq,5,2,8,2,2,2,1,6

In [7]:
df.head(20)

,Financial instrument,Current price,Change(%),Open,High,Low,Volume,Market Cap.
1,1-800-FLOWERS.COM,4.27,-1.16%,4.41,4.41,4.20,"222,698",233M
2,10X GENOMICS,32.22,+11.72%,29.73,32.33,29.73,"4,477,135","3,708M"
3,111,4.57,-6.54%,4.81,4.99,4.43,"22,777",39M
4,17 EDUCATION & TECHNOLOGY,2.39,+1.70%,2.41,2.41,2.35,"3,079",22M
5,1RT ACQUISITION,10.23,+0.00%,10.23,10.23,10.23,"2,113",145M
6,1RT ACQUISITION,10.32,-0.10%,10.32,10.32,10.32,"2,800",147M
7,1ST SOURCE,77.40,-1.43%,78.69,79.08,77.21,"122,721","1,368M"
8,1STDIBS.COM,4.09,+0.25%,4.08,4.23,4.07,"111,962",92M
9,20/20 BIOLABS,0.5957,-38.12%,0.7742,0.7893,0.5660,"3,552,263",3M
10,22ND CENTURY,6.14,-6.26%,6.59,6.60,6.10,"50,446",1M
11,3 E NETWORK TECHNOLOGY,2.41,+1.69%,2.37,2.46,2.25,"899,469","120,435"
12,36KR,2.99,+2.05%,2.91,3.48,2.83,"148,321",3M
13,374WATER,2.31,+0.00%,2.35,2.47,2.22,"101,310",21M
14,4D MOLECULAR THERAPEUTICS,9.22,+4.42%,9.04,9.80,9.04,"1,064,885",358M
15,5E ADVANCED MATERIALS,1.71,+0.59%,1.73,1.77,1.71,"98,316",11M
16,60 DEGREES PHARMACEUTICALS,1.49,+9.56%,1.43,1.49,1.37,"85,626",1M
17,707 CAYMAN,2.19,+0.46%,2.10,2.47,2.10,"231,765",1M
18,8X8,1.77,-0.56%,1.80,1.86,1.77,"1,206,364",240M
19,908 DEVICES,8.62,+4.23%,8.62,8.78,8.46,"159,356",243M
20,9F,2.88,-2.04%,3.20,3.20,2.88,"4,139",13M